# Generated by Django 3.2.8 on 2022-06-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220629_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrie',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
