# Generated by Django 3.2.8 on 2022-06-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_countrie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='flight_id',
            new_name='flight',
        ),
    ]
