# Generated by Django 3.2.8 on 2022-06-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220629_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline_companie',
            old_name='countrie_id',
            new_name='countrie',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airline_Companie_id',
            new_name='airline_Companie',
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_countrie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_countrie', to='base.countrie'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_countrie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_countrie', to='base.countrie'),
        ),
    ]
