# Generated by Django 3.2.8 on 2022-07-02 13:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220629_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='remaining_tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MinValueValidator(1)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='flight',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flight'),
        ),
    ]
