# Generated by Django 3.2.8 on 2022-07-09 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_tickets_number_of_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flight'),
        ),
    ]
