# Generated by Django 3.2.8 on 2022-08-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_flight_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_card_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
