# Generated by Django 3.2.8 on 2022-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20220820_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_card_No',
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
